---
- name: deploy service and deployment files
  hosts: all
  become: true
  tasks:
    - name: Copy deployment YAML file to root user's home directory on remote machine
      copy:
        src:  deployment.yml
        dest: /root/kubernetes.yml

    - name: Apply kubernetes deployment and YAML with kubectl
      command: kubectl apply -f /root/kubernetes.yml
