---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-deploy
  labels:
    app: healthcare-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
        - name: healthcare-container
          image: anjalibhat/healthcare-app:latest
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
  labels:
    app: healthcare-app
spec:
  selector:
    app: healthcare-app
  type: NodePort
  ports:
    - nodePort: 31032
      port: 8082
      targetPort: 8082
