---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-deploy
  labels:
    app: healthcare-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
        - name: healthcare-container
          image: anjalibhat/healthcare-app:latest
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
  labels:
    app: healthcare-app
spec:
  selector:
    app: healthcare-app
  type: NodePort
  ports:
    - nodePort: 31032
      port: 8082
      targetPort: 8082

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090
        env:
        - name: TZ
          value: "UTC"

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
  type: NodePort
