
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-np-service
  labels:
    app: healthcare-app
spec:
  selector:
    app: healthcare-app
  type: NodePort
  ports:
    - nodePort: 31037
      port: 8083
      targetPort: 8083
