---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
  labels:
    app: healthcare-app
spec:
  selector:
    app: healthcare-app
  type: NodePort
  ports:
    - nodePort: 31032
      port: 8082
      targetPort: 8082
